version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: '27017'
    volumes:
      - mongodata:/data/db
    ports:
      - '0.0.0.0:27017:27017'

  express:
    build:
      context: './rest'
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
    ports:
      - '5000:5000'
    volumes:
      - keydata:/app/keys
      - serverdata:/app/public

  socket:
    build:
      context: './socket-io'
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - mongo
      - express
    environment:
      - CONNECTION_STRING=mongo
      - DEBUG=*
    ports:
      - '8080:8080'
    volumes:
      - keydata:/app/keys

  react:
    build:
      context: './chat'
      dockerfile: dockerfile
    ports:
      - '3000:3000'

volumes:
  mongodata:
  keydata:
  serverdata:
