version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: dev-db
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: '27017'
    volumes:
      - mongodata:/data/db
    ports:
      - '0.0.0.0:27017:27017'

volumes:
  mongodata:
